### ISSUE TITLE
Seems like error handling doesn't work

### ISSUE THREAD

**Issue by Teq** [Wizcorp/node-graylog2#11]
I am running this code:

``` javascript
var graylog2 = require("graylog2");

var logger = new graylog2.graylog({
    servers: [{ host: 'localhost', port: 9999 }]
});

logger.on('error', function (error) {
    console.log('Error:', error);
});

logger.emergency("App crashed");

logger.close(function(){
    console.log('All good, exiting');
    process.exit();
});
```

And I can set any random ip/port combination (even unreachable host) and it doesn't trigger errors at all, just 'All good, exiting'. Maybe I am doing something wrong or my expectations are wrong?

P.S. It would be good to indicate somewhere on front page that this library can be used only with UDP graylog inputs.

**Comment by erwinw** [comment]
Not the developer, but since you're using a hard-core process.exit, it might be that the app exits before you even get to see any errors? Try removing it and see.

**Comment by Teq** [comment]
@erwinw , Tried without explicit `process.exit()`, nothing changed. Now I think that the behavior is correct because UDP (as I recall) has no error correction and there is no way to check if datagram is received on server side.
