### ISSUE TITLE
Optional console logging

### ISSUE THREAD

**Issue by alexcroox** [Wizcorp/node-graylog2#12]
Would be great if you could also console log messages during development so if you don't have access to graylog you can instantly get feedback without duplicating logging messages.

**Comment by stelcheck** [comment]
I would recommend against it.

It would be much better to write your own logging layer to remain in control of the logging logic over time. node-graylog2 is not meant to be a replacement for console.log/error/etc.

**Comment by alexcroox** [comment]
Agreed
