### ISSUE TITLE
Doesn't close doesn't destroy if nothing to send

### ISSUE THREAD

**Issue by erwinw** [Wizcorp/node-graylog2#13]
The `.close` method does not actually close the connection and call a possible callback if no unsent messages/chunks are left.

**Comment by ronkorving** [comment]
Ouch, that's a problem. Mind sending a PR to address this?

**Comment by stelcheck** [comment]
Looks like there is a PR for that, and one that has been up since April. Already pinged it, suggest you have a second look at it.

**Comment by ronkorving** [comment]
I think that's a different issue.

**Comment by erwinw** [comment]
Created a PR, @ronkorving .

**Comment by ronkorving** [comment]
Thanks!

**Comment by ronkorving** [comment]
Is it me or...? I don't see it.
