### ISSUE TITLE
CallCount++ will eventually break

### ISSUE THREAD

**Issue by jasonmcaffee** [Wizcorp/node-graylog2#18]
Probably not a huge priority, but while investigating a memory leak somewhere in winston, I noticed the getServer code using a clever way of load balancing between configured servers.
CallCount is never reset though, so once the count reaches 9007199254740992, callCount++ will stop incrementing, thus breaking load balancing.
https://github.com/Wizcorp/node-graylog2/blob/master/graylog.js#L49

**Comment by ronkorving** [comment]
Yeah, that's a crazy high number, but you're not incorrect :)
Basically it boils down to being able to send 1 million logs per second per process for 285 years. I hope that anyone logging that much with this library, is willing to put in a PR to fix this ;)

**Comment by jasonmcaffee** [comment]
I'm looking into a significant memory leak in your module when running inside of a docker 1.11 container, and there is no graylog server running to accept messages.

I've been able to rule out dgram, going to take a look at zlib next...

**Comment by jasonmcaffee** [comment]
The memory leak issue is with zlib.deflate.

Just doing this inside of docker (latest node) eats up 1GB of ram on my macbook pro, and it never releases
```
let zlib = require('zlib');

let message = {
  some:"data"
};
let payload = new Buffer(JSON.stringify(message));

for(var i =0; i < 10000; ++i){
  zlib.deflate(payload, function (err, buffer) {
  });
}
```

**Comment by ronkorving** [comment]
As @bnoordhuis explained, this is not that strange. You're deflating 10000 times in parallel. Anyway, unrelated to node-graylog2.

**Comment by jasonmcaffee** [comment]
@ronkorving I'm not sure what you mean. Using your package causes our services to crash after about a week of logging (our services aren't heavily utilized at the moment, so its not even a large amount of logging). Your package uses graylog2, which uses zlib deflate.  Anyone who uses your package on a Linux system will be affected by this issue. If you changed your package to replace graylog2 with another package that doesn't use zlib deflate, there would be no issue.

**Comment by ronkorving** [comment]
Let's discuss that in issue #19, where it belongs. I'm gonna close this one.
