### ISSUE TITLE
Random EADDRINUSE errors when logging

### ISSUE THREAD

**Issue by FredrikL** [Wizcorp/node-graylog2#26]
Hi

I have a small problem with random crashes wit a EADDRINUSE error. The environment consists of multiple services run with pm2 and scripts started from cron. In both cases i see errors once or twice per day. The error is as below.

```
bind EADDRINUSE 0.0.0.0
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at dgram.js:221:18
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I haven't been able to confirm it but from the [dgram docs](https://nodejs.org/api/dgram.html#dgram_dgram_createsocket_options_callback) I think it might be solve by setting `reuseAddr` to true

**Comment by ronkorving** [comment]
The problem may be more related to your environment than this library. However, I can imagine using `reuseAddr` would "solve" (ie: work around) your problem.

So, a reuseAddr boolean could be introduced to the config object passed to the constructor, but I would still argue that you probably want to investigate your setup.

**Comment by FredrikL** [comment]
Sorry, seems to be a fault on my end, found a function that didn't close the logger after use seems to have been the problem
