### ISSUE TITLE
node-graylo2 not sending messages in correct format to Graylog2

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [Wizcorp/node-graylog2#32]
Hi, I just recently tried your package with the following code snippet:

```
const graylog2 = require("graylog2");

const logger = new graylog2.graylog({
    servers: [
        { "host": "52.136.248.240", port: 8514 }
    ],
    // hostname: "test.name", // the name of this host
    // (optional, default: os.hostname())
    facility: "Banana.js",     // the facility for these log messages
    // (optional, default: "Node.js")
    // bufferSize: 1350         // max UDP packet size, should never exceed the
    // MTU of your system (optional, default: 1400)
});

logger.on("error", function (error) {
    console.error("Error while trying to write to graylog2:", error);
});

logger.log("InvalidChecksum", JSON.stringify({ name: "Error", message: "The packet is corrupted. CRC-16-IBM not matching.", info: 1 }));

logger.close(function(){
    console.log('All done - cookie now?');
    process.exit();
});
```

So, as you can see, there are several things I ought to expect when check the graylog logs, like for example, the facility being "Banana.js".

This however, is not the case. graylog2 seems to be unable to understand my log, and parses everything as a single string. I have attached a screenshot that exemplifies this:

![bug](https://user-images.githubusercontent.com/2980392/39309180-a9621f08-4967-11e8-8682-9bd62000276c.PNG)

From the image, you can see that a few things are not quite right:

1. facility is Unknown
2. level is -1
3. If show the column "Full message", it will be empty

I assume this is either a config issue, or the module is not communication correctly with graylog2.

**Comment by stelcheck** [comment]
Apologies for the late response.

At the moment I don't have the time to investigate your issue, but I will be happy to review and merge any fixes you would send our way :)

**Comment by Fl4m3Ph03n1x** [comment]
Hello, it turns out that the issue was that my graylog app was of type Syslog UDP instead of being of type GELF UDP. 

This caused the app to incorrectly interpret the results. 

I think it would be beneficial to include in the docs that if you use this package the app should have a GELF UDP Input type to prevent nooby questions like this one. 

Thanks for the attention, I will close the ticket!

**Comment by ronkorving** [comment]
@Fl4m3Ph03n1x Thanks for the update, I'm glad it all worked out! Would you mind making a small PR to the ReadMe to document the issue so others can be spared the same fate?

**Comment by Fl4m3Ph03n1x** [comment]
Absolutely, will do it once I have a chance. I will leave this open in the meantime as a reminder.

**Comment by Fl4m3Ph03n1x** [comment]
I tried pushing my work to a new branch called "update-readme" but unfortunatly I don't have permissions to do so ( 403 forbidden ). 

Given that I can't push my work to a new branch and thus cannot create a pull request, could you give me permissions to do so?

**Comment by ronkorving** [comment]
You'll want to fork this repository, push to your fork, and then make a pull request from there.

**Comment by Fl4m3Ph03n1x** [comment]
Done! 
Please review at your earliest convinience !

**Comment by ronkorving** [comment]
Thanks for the PR. Merged it :)

**Comment by Fl4m3Ph03n1x** [comment]
My pleasure. Always happy to help :D
